name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  Jest:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |
          sudo apt-get update && sudo apt-get install -y libreoffice
          npm install 
          npm test